# This was based on: python-libzim test workflow.
# https://github.com/openzim/python-libzim/blob/master/.github/workflows/test.yml

name: test
on: [push]
env:
  MAX_LINE_LENGTH: 110

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
          architecture: x64

      - name: Linter with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --exclude=setup.py --show-source --statistics
          flake8 . --count --exclude=setup.py --max-line-length=$MAX_LINE_LENGTH --statistics
